services:
  influxdb:
    build:
      context: ./influx
    container_name: mav-influx
    ports:
      - "8181:8181"
    environment:
      INFLUXDB_NODE_ID: mav-node
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: admin123
      DOCKER_INFLUXDB_INIT_ORG: mav-org
      DOCKER_INFLUXDB_INIT_BUCKET: sample-bucket
      DOCKER_INFLUXDB_INIT_RETENTION: 72h
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: supersecrettoken
    command: ["influxdb3", "serve", "--node-id-from-env", "INFLUXDB_NODE_ID", "--disable-authz", "health,ping"]
    volumes:
      - influx-data:/var/lib/influxdb3
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8181/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  influxdb3-ui:
    image: influxdata/influxdb3-ui:latest
    container_name: mav-influxdb-ui
    depends_on:
      influxdb:
        condition: service_healthy
    ports:
      - "8888:80"
      - "8889:8888"
    restart: unless-stopped

  grafana:
    image: grafana/grafana:11.0.0
    container_name: mav-grafana
    depends_on:
      influxdb:
        condition: service_healthy
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin123
      INFLUXDB_URL: http://influxdb:8181
      INFLUXDB_TOKEN: supersecrettoken
      INFLUXDB_ORG: mav-org
      INFLUXDB_BUCKET: sample-bucket
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - grafana-data:/var/lib/grafana

  alert-api:
    build:
      context: .
      dockerfile: alert-api/Dockerfile
    container_name: mav-alert-api
    depends_on:
      influxdb:
        condition: service_healthy
    volumes:
      - alert-api-logs:/app/logs
    environment:
      INFLUX_URL: http://influxdb:8181
      INFLUX_TOKEN: supersecrettoken
      INFLUX_ORG: mav-org
    ports:
      - "9000:9000"

volumes:
  influx-data:
  grafana-data:
  alert-api-logs:

