apiVersion: 1

datasources:
  - name: InfluxDB
    uid: influxdb-flux
    type: influxdb
    access: proxy
    url: ${INFLUXDB_URL}
    jsonData:
      version: Flux
      organization: ${INFLUXDB_ORG}
      defaultBucket: ${INFLUXDB_BUCKET}
    secureJsonData:
      token: ${INFLUXDB_TOKEN}

